export const MODULES = [
  // ─── VIDEO MODULES ───
  {
    id: 'v-intro',
    type: 'video',
    title: 'New Hire Training',
    desc: 'Comprehensive onboarding session — insurance fundamentals, Harper workflows, carrier routing, and service standards.',
    icon: '▶️',
    driveId: '1heqi22KnVnPOzrdgoV1eTAJnXG-DmsyR',
    badge: { label: 'INTRO', cls: 'b-coral' },
  },
  {
    id: 'v-1',
    type: 'video',
    title: 'General Liability Insurance',
    desc: 'What general liability covers, what it protects, and why every business needs it.',
    icon: '1️⃣',
    driveId: '1D0LBjQuMMUDSoTsVsfMEnjAjRJKE7ioC',
    badge: { label: 'MODULE 1', cls: 'b-green' },
  },
  {
    id: 'v-2',
    type: 'video',
    title: 'Professional Liability & E&O',
    desc: 'Errors & omissions coverage, who needs it, and how it differs from GL.',
    icon: '2️⃣',
    driveId: '19jUhZs79_kYU7M4tMgNQgOmWo0BoBr7L',
    badge: { label: 'MODULE 2', cls: 'b-green' },
  },
  {
    id: 'v-3',
    type: 'video',
    title: 'EPLI',
    desc: 'Employment Practices Liability Insurance — protecting businesses from employee-related claims.',
    icon: '3️⃣',
    driveId: '10fik_h9AiCXRt31aB3o0hLnAL8PFSLf_',
    badge: { label: 'MODULE 3', cls: 'b-green' },
  },
  {
    id: 'v-4',
    type: 'video',
    title: 'Directors & Officers Insurance',
    desc: 'D&O coverage for company leaders — what it covers and when it applies.',
    icon: '4️⃣',
    driveId: '1mT7nzY7Qfp11Vr4sviuMLDzol-uvLyOL',
    badge: { label: 'MODULE 4', cls: 'b-green' },
  },
  {
    id: 'v-5',
    type: 'video',
    title: 'Liquor Liability',
    desc: 'Essentials for businesses that serve, sell, or distribute alcohol.',
    icon: '5️⃣',
    driveId: '1k1nYQYAuf0bEeDeUnDsGbzrci0eTu38a',
    badge: { label: 'MODULE 5', cls: 'b-green' },
  },
  {
    id: 'v-6',
    type: 'video',
    title: 'Claims-Made Policies',
    desc: 'Claims-made vs. occurrence policies — how coverage triggers work.',
    icon: '6️⃣',
    driveId: '1nPW-BmIgl0jvHAhBnLUnGrSRKz72XwL5',
    badge: { label: 'MODULE 6', cls: 'b-green' },
  },
  {
    id: 'v-7',
    type: 'video',
    title: 'Business Income',
    desc: 'Business income and extra expense coverage — protecting revenue when operations are disrupted.',
    icon: '7️⃣',
    driveId: '1irh5YwlKsLQHGyx9OnITRoPydT-y_YPz',
    badge: { label: 'MODULE 7', cls: 'b-green' },
  },
  {
    id: 'v-8',
    type: 'video',
    title: 'Cyber Liability',
    desc: 'Cyber liability coverage for data breaches, ransomware, and digital risks.',
    icon: '8️⃣',
    driveId: '1kyDvwGPYnA6VeAxjYM0Fx-GDmU-SwnZp',
    badge: { label: 'MODULE 8', cls: 'b-green' },
  },
  {
    id: 'v-9',
    type: 'video',
    title: 'Inland Marine',
    desc: 'Covering equipment, tools, and property in transit.',
    icon: '9️⃣',
    driveId: '1tg90UV9kG4FTwtkttgrSiLM8Rc6UEoOE',
    badge: { label: 'MODULE 9', cls: 'b-green' },
  },
  {
    id: 'v-10',
    type: 'video',
    title: 'Building & BPP Coverage',
    desc: 'Building and business personal property — protecting physical assets.',
    icon: '🔟',
    driveId: '1tnz_ug1y-_st_Cyrd_UvR2RnBmV9pI0o',
    badge: { label: 'MODULE 10', cls: 'b-green' },
  },
  {
    id: 'v-11',
    type: 'video',
    title: 'Common Intake Mistakes',
    desc: 'Common mistakes during intake and how to avoid them.',
    icon: '⚠️',
    driveId: '1oCHd2RXgo9oRxk9ITWTpU9R3f6msWeQt',
    badge: { label: 'MODULE 11', cls: 'b-orange' },
  },

  // ─── READING MODULES ───
  {
    id: 'r-101',
    type: 'reading',
    title: '101 — Fundamentals',
    desc: 'How Harper makes money, customer lifecycle, policy types, billing, revenue, risk, and sales requirements.',
    icon: '📘',
    component: 'Module101',
    badge: { label: 'READING', cls: 'b-blue' },
    quiz: [
      { q: "What are Harper's two revenue channels?", options: ['Salary and tips', 'Commission and broker fees', 'Referral bonuses and advertising', 'Subscription fees'], answer: 1 },
      { q: 'What happens if a policy cancels early?', options: ['Harper keeps full commission', 'Customer gets a bonus', 'Harper must repay commission (chargeback)', 'Nothing'], answer: 2 },
      { q: 'What is the ideal customer retention length?', options: ['1–2 years', '3–5 years', '7–9 years', '15+ years'], answer: 2 },
      { q: 'What should you always try before going E&S?', options: ['Agency bill', 'Direct bill', 'Premium financing', 'Surplus lines'], answer: 1 },
      { q: 'What differentiates Harper from other agencies?', options: ['Lower prices', 'Speed and response time', 'More carriers', 'Bigger office'], answer: 1 },
    ],
  },
  {
    id: 'r-102',
    type: 'reading',
    title: '102 — Coverage Types',
    desc: 'COI fundamentals, additional insured, core liability types, workers\' comp, property, and specialty coverage.',
    icon: '📗',
    component: 'Module102',
    badge: { label: 'READING', cls: 'b-blue' },
    quiz: [
      { q: 'A Certificate of Insurance (COI) does what?', options: ['Grants additional coverage', 'Replaces the policy', 'Proves coverage exists but does NOT grant it', 'Cancels existing policy'], answer: 2 },
      { q: 'What is the standard GL limit?', options: ['$500K/$1M', '$1M/$2M', '$2M/$5M', '$5M/$10M'], answer: 1 },
      { q: 'What does a Waiver of Subrogation do?', options: ['Gives a discount', 'Carrier agrees not to sue a specific party after paying a claim', 'Type of additional insured', 'Cancels coverage'], answer: 1 },
      { q: "Why are Workers' Comp payroll audits dangerous?", options: ['They reduce limits', 'They cancel the policy', 'Understating payroll triggers adjustment bills and blocks future coverage', 'They increase broker fees'], answer: 2 },
      { q: 'When should you push liquor liability?', options: ['Only for bars', 'For every restaurant serving ANY alcohol', 'Only if customer asks', 'Never'], answer: 1 },
    ],
  },
  {
    id: 'r-201',
    type: 'reading',
    title: '201 — Carriers & Operations',
    desc: 'Billing paths, routing logic, direct carriers, MGAs, E&S market, appetite guide, and service operations.',
    icon: '📙',
    component: 'Module201',
    badge: { label: 'READING', cls: 'b-blue' },
    quiz: [
      { q: 'What is the correct routing order?', options: ['E&S first then direct', 'Direct bill first, E&S last resort', 'Agency bill always', 'Whatever is cheapest'], answer: 1 },
      { q: "What carrier writes Workers' Comp exclusively?", options: ['Next', 'Coterie', 'Employers', 'Chubb'], answer: 2 },
      { q: 'What is the COI issuance target time?', options: ['Same day', '5 minutes', '1 hour', '24 hours'], answer: 1 },
      { q: 'Why is Kinsale considered a last resort?', options: ['Best prices', 'Expensive, heavy exclusions, never returns money', 'Only writes one state', 'Not a real carrier'], answer: 1 },
      { q: 'What is the same-day completion standard?', options: ['All requests started same day', 'All requests completed same day — nothing overnight unless blocked', 'Respond within 24 hours', 'Acknowledge same day'], answer: 1 },
    ],
  },
  {
    id: 'r-203',
    type: 'reading',
    title: '203 — Sales & Account Management',
    desc: 'Sales pitch framework, cross-selling, post-sale handoff, cancellations, reinstatements, and customer relationships.',
    icon: '📕',
    component: 'Module203',
    badge: { label: 'READING', cls: 'b-blue' },
    quiz: [
      { q: 'What must you legally disclose during a sale?', options: ['Your commission', 'The $100 broker fee', "Carrier's profit margin", 'Your personal opinion'], answer: 1 },
      { q: 'How should you handle "it\'s too expensive"?', options: ['Lower price immediately', 'Name the 5 carriers you shopped to show due diligence', 'Tell them to go elsewhere', 'Ignore it'], answer: 1 },
      { q: 'What is the most common intake error?', options: ['Wrong phone number', 'Incorrect business name (DBA vs legal entity)', 'Missing email', 'Wrong zip code'], answer: 1 },
      { q: 'How many days is the initial grace period for missed payments?', options: ['3 days', '5 days', '10 days', '30 days'], answer: 1 },
      { q: 'What is the same-day response rule?', options: ['Respond within 24 hours', 'Every customer who reaches out must be touched same day', 'Only urgent requests same day', 'Within the work week'], answer: 1 },
    ],
  },

  // ─── FINAL EXAM ───
  {
    id: 'final-exam',
    type: 'exam',
    title: 'Final Exam',
    desc: 'Comprehensive exam covering all modules. 10 random questions, 80% to pass.',
    icon: '🎓',
    badge: { label: 'FINAL', cls: 'b-coral' },
  },
]
