export const MODULES = [
  // ─── VIDEO MODULES ───
  {
    id: 'v-intro',
    type: 'video',
    title: 'New Hire Training',
    desc: 'Comprehensive onboarding session — insurance fundamentals, Harper workflows, carrier routing, and service standards.',
    icon: '▶️',
    driveId: '1heqi22KnVnPOzrdgoV1eTAJnXG-DmsyR',
    badge: { label: 'INTRO', cls: 'b-coral' },
  },
  {
    id: 'v-1',
    type: 'video',
    title: 'General Liability Insurance',
    desc: 'What general liability covers, what it protects, and why every business needs it.',
    icon: '1️⃣',
    driveId: '1D0LBjQuMMUDSoTsVsfMEnjAjRJKE7ioC',
    badge: { label: 'MODULE 1', cls: 'b-green' },
  },
  {
    id: 'v-2',
    type: 'video',
    title: 'Professional Liability & E&O',
    desc: 'Errors & omissions coverage, who needs it, and how it differs from GL.',
    icon: '2️⃣',
    driveId: '19jUhZs79_kYU7M4tMgNQgOmWo0BoBr7L',
    badge: { label: 'MODULE 2', cls: 'b-green' },
  },
  {
    id: 'v-3',
    type: 'video',
    title: 'EPLI',
    desc: 'Employment Practices Liability Insurance — protecting businesses from employee-related claims.',
    icon: '3️⃣',
    driveId: '10fik_h9AiCXRt31aB3o0hLnAL8PFSLf_',
    badge: { label: 'MODULE 3', cls: 'b-green' },
  },
  {
    id: 'v-4',
    type: 'video',
    title: 'Directors & Officers Insurance',
    desc: 'D&O coverage for company leaders — what it covers and when it applies.',
    icon: '4️⃣',
    driveId: '1mT7nzY7Qfp11Vr4sviuMLDzol-uvLyOL',
    badge: { label: 'MODULE 4', cls: 'b-green' },
  },
  {
    id: 'v-5',
    type: 'video',
    title: 'Liquor Liability',
    desc: 'Essentials for businesses that serve, sell, or distribute alcohol.',
    icon: '5️⃣',
    driveId: '1k1nYQYAuf0bEeDeUnDsGbzrci0eTu38a',
    badge: { label: 'MODULE 5', cls: 'b-green' },
  },
  {
    id: 'v-6',
    type: 'video',
    title: 'Claims-Made Policies',
    desc: 'Claims-made vs. occurrence policies — how coverage triggers work.',
    icon: '6️⃣',
    driveId: '1nPW-BmIgl0jvHAhBnLUnGrSRKz72XwL5',
    badge: { label: 'MODULE 6', cls: 'b-green' },
  },
  {
    id: 'v-7',
    type: 'video',
    title: 'Business Income',
    desc: 'Business income and extra expense coverage — protecting revenue when operations are disrupted.',
    icon: '7️⃣',
    driveId: '1irh5YwlKsLQHGyx9OnITRoPydT-y_YPz',
    badge: { label: 'MODULE 7', cls: 'b-green' },
  },
  {
    id: 'v-8',
    type: 'video',
    title: 'Cyber Liability',
    desc: 'Cyber liability coverage for data breaches, ransomware, and digital risks.',
    icon: '8️⃣',
    driveId: '1kyDvwGPYnA6VeAxjYM0Fx-GDmU-SwnZp',
    badge: { label: 'MODULE 8', cls: 'b-green' },
  },
  {
    id: 'v-9',
    type: 'video',
    title: 'Inland Marine',
    desc: 'Covering equipment, tools, and property in transit.',
    icon: '9️⃣',
    driveId: '1tg90UV9kG4FTwtkttgrSiLM8Rc6UEoOE',
    badge: { label: 'MODULE 9', cls: 'b-green' },
  },
  {
    id: 'v-10',
    type: 'video',
    title: 'Building & BPP Coverage',
    desc: 'Building and business personal property — protecting physical assets.',
    icon: '🔟',
    driveId: '1tnz_ug1y-_st_Cyrd_UvR2RnBmV9pI0o',
    badge: { label: 'MODULE 10', cls: 'b-green' },
  },
  {
    id: 'v-11',
    type: 'video',
    title: 'Common Intake Mistakes',
    desc: 'Common mistakes during intake and how to avoid them.',
    icon: '⚠️',
    driveId: '1oCHd2RXgo9oRxk9ITWTpU9R3f6msWeQt',
    badge: { label: 'MODULE 11', cls: 'b-orange' },
  },
  {
    id: 'v-12',
    type: 'video',
    title: 'Garage Insurance',
    desc: 'Garage insurance coverage for auto service businesses, dealerships, and repair shops.',
    icon: '🔧',
    driveId: '1L_qE5C1PCsNzs6LGv7CgafFMHz5mJdaa',
    badge: { label: 'MODULE 12', cls: 'b-green' },
  },
  {
    id: 'v-13',
    type: 'video',
    title: 'A Guide to Insurance Intake',
    desc: 'Complete guide to the insurance intake process — collecting information, setting expectations, and moving leads forward.',
    icon: '📋',
    driveId: '1zzDvRXcSP1W8h28qQ_rOHvfhdZaY6apd',
    badge: { label: 'MODULE 13', cls: 'b-green' },
  },

  // ─── INTAKE TRAINING VIDEOS ───
  {
    id: 'it-1',
    type: 'video',
    group: 'intake-training',
    title: 'Security Guard Intake',
    desc: 'Intake walkthrough for security guard businesses — what to collect, what to verify, and common pitfalls.',
    icon: '🛡️',
    driveId: '15naKHMQM1_TE2vGlwBoWmYdgkc831VXj',
    badge: { label: 'INTAKE 1', cls: 'b-orange' },
  },
  {
    id: 'it-2',
    type: 'video',
    group: 'intake-training',
    title: 'Garage Liability Intake',
    desc: 'Intake walkthrough for garage and auto service businesses — dealer bonds, garagekeepers, and liability coverage.',
    icon: '🔧',
    driveId: '1wGCrOAWpnujnRDrd8M5_WeZLTqEIUZd9',
    badge: { label: 'INTAKE 2', cls: 'b-orange' },
  },
  {
    id: 'it-3',
    type: 'video',
    group: 'intake-training',
    title: 'Restaurant & Property Intake',
    desc: 'Intake walkthrough for restaurants and property coverage — liquor liability, building coverage, and BPP.',
    icon: '🍽️',
    driveId: '1SPQbrSVc4iceHUXijP29gTrim2D2TTET',
    badge: { label: 'INTAKE 3', cls: 'b-orange' },
  },
  {
    id: 'it-4',
    type: 'video',
    group: 'intake-training',
    title: 'Workers Compensation Intake',
    desc: 'Intake walkthrough for workers\' comp — payroll verification, audit prep, and owner inclusion/exclusion.',
    icon: '⚠️',
    driveId: '1obIEprqwCnjpkbf1EGTvqEwYGYqllfnI',
    badge: { label: 'INTAKE 4', cls: 'b-orange' },
  },

  // ─── READING MODULES ───
  {
    id: 'r-101',
    type: 'reading',
    title: '101 — Fundamentals',
    desc: 'How Harper makes money, customer lifecycle, policy types, billing, revenue, risk, and sales requirements.',
    icon: '📘',
    component: 'Module101',
    badge: { label: 'READING', cls: 'b-blue' },
    quiz: [
      { q: 'On a direct bill policy, when does Harper receive the commission?', options: ['Instantly at binding', 'About one month after the policy is issued', 'At the end of the policy term', '90 days after issuance'], answer: 1 },
      { q: 'What is a chargeback and when does it happen?', options: ['A fee for late payments', 'Harper must repay commission to the carrier when a policy cancels early', 'A penalty for incorrect COIs', 'An additional charge on agency bill policies'], answer: 1 },
      { q: 'If a broker fee is structured as "unearned," how is it collected?', options: ['100% upfront at binding', 'Paid to Harper on a monthly basis', 'Deducted from the commission', 'Paid at policy renewal'], answer: 1 },
      { q: 'In the premium financing flow, who does the finance company pay first?', options: ['The insurance carrier directly', 'The customer as a refund', 'The broker, who then pays the carrier', 'Harper as commission'], answer: 2 },
      { q: 'Why is it critical to not let customers understate their revenue during intake?', options: ['It increases the broker fee', 'It knocks them out of quotes they could have qualified for and produces incorrect quotes', 'It triggers an automatic audit', 'It violates surplus lines regulations'], answer: 1 },
    ],
  },
  {
    id: 'r-102',
    type: 'reading',
    title: '102 — Coverage Types',
    desc: 'COI fundamentals, additional insured, core liability types, workers\' comp, property, and specialty coverage.',
    icon: '📗',
    component: 'Module102',
    badge: { label: 'READING', cls: 'b-blue' },
    quiz: [
      { q: 'What is the danger of listing wrong limits on a COI?', options: ['The customer pays more', 'It creates E&O liability — Harper can be sued for the difference', 'The policy automatically cancels', 'The carrier issues a refund'], answer: 1 },
      { q: 'What is the difference between a blanket additional insured and a specifically listed one?', options: ['Blanket is cheaper', 'Blanket auto-extends AI to anyone with a written contract; specific requires exact entity name and address', 'There is no difference', 'Specific is only for E&S policies'], answer: 1 },
      { q: 'What happens if a customer understates payroll on a workers\' comp policy?', options: ['Nothing until renewal', 'The annual audit catches it, triggering adjustment bills and potentially blocking future WC coverage nationally', 'The carrier adjusts it automatically', 'Only the broker fee increases'], answer: 1 },
      { q: 'What does EPLI protect a business against?', options: ['Property damage from employees', 'Wrongful termination, discrimination, and harassment claims from employees', 'Cyber attacks from former employees', 'Employee theft of inventory'], answer: 1 },
      { q: 'What is the difference between replacement cost and actual cash value (ACV) on a property policy?', options: ['They mean the same thing', 'Replacement cost pays for a brand new item; ACV pays only the depreciated current value', 'ACV always pays more', 'Replacement cost only applies to buildings, not contents'], answer: 1 },
    ],
  },
  {
    id: 'r-201',
    type: 'reading',
    title: '201 — Carriers & Operations',
    desc: 'Billing paths, routing logic, direct carriers, MGAs, E&S market, appetite guide, and service operations.',
    icon: '📙',
    component: 'Module201',
    badge: { label: 'READING', cls: 'b-blue' },
    quiz: [
      { q: 'Why must you exhaust quick-market carriers before routing to E&S?', options: ['E&S is illegal in most states', 'Quick markets deliver instant quotes with better coverage, no surplus line taxes, and simpler operations', 'E&S carriers require a minimum $10K premium', 'Quick markets pay higher commission'], answer: 1 },
      { q: 'What is the key limitation of Coterie when it comes to endorsements?', options: ['They cannot write GL', 'Name changes require a full cancel and rewrite of the policy', 'They only write in 10 states', 'Endorsements are free but take 30 days'], answer: 1 },
      { q: 'What is the service standard for completing requests received during business hours?', options: ['Within 48 hours', 'Acknowledged same day, completed within a week', 'Completed the same day — nothing sits overnight unless blocked by an external party', 'Started same day, finished next morning'], answer: 2 },
      { q: 'Why must cancellation contact attempts be applied consistently to ALL pending cancellations?', options: ['It reduces chargebacks', 'If you contact some but miss others, the ones you missed can sue Harper for not being notified', 'It is a carrier requirement for commission', 'It improves renewal rates'], answer: 1 },
      { q: 'What makes Chubb unique among Harper\'s direct carrier partners?', options: ['They write the cheapest policies', 'They are the #1 cyber writer nationally and require $50K volume for full appointment', 'They only write workers\' comp', 'They offer instant binding for all lines'], answer: 1 },
    ],
  },
  {
    id: 'r-202',
    type: 'reading',
    title: '202 — Sales & Account Management',
    desc: 'Sales pitch framework, cross-selling, post-sale handoff, cancellations, reinstatements, and customer relationships.',
    icon: '📕',
    component: 'Module203',
    badge: { label: 'READING', cls: 'b-blue' },
    quiz: [
      { q: 'What is the single most important thing to verify before presenting a quote?', options: ['The customer\'s email address', 'That all coverage needs, landlord requirements, and contract requirements are captured correctly', 'The carrier\'s commission rate', 'Whether the customer has an existing policy'], answer: 1 },
      { q: 'On an agency bill cancellation, why must you proactively remove autopay from premium finance?', options: ['It voids the policy immediately', 'If you don\'t, the customer keeps getting charged for up to 60 more days after requesting cancellation', 'It triggers a chargeback', 'The carrier requires it before processing'], answer: 1 },
      { q: 'What happens after 30 days of non-payment on a policy?', options: ['The carrier waives the balance', 'A late fee is applied and the policy continues', 'Reinstatement becomes very unlikely — the policy must be re-quoted and re-bound from scratch', 'The broker fee covers the gap'], answer: 2 },
      { q: 'When a customer says "just email me the quote," what is the correct response?', options: ['Email it and wait', 'Walk them through the quote on the phone first so they understand it, then email it', 'Refuse to email anything', 'Send it to their spouse instead'], answer: 1 },
      { q: 'Why is it dangerous to confuse a DBA with a legal entity name during intake?', options: ['It changes the premium amount', 'It makes every downstream document wrong — accords, quotes, applications, and bind requests all need correction', 'The carrier charges a name-change fee', 'It only matters for E&S policies'], answer: 1 },
    ],
  },

  // ─── FINAL EXAM ───
  {
    id: 'final-exam',
    type: 'exam',
    title: 'Final Exam',
    desc: 'Comprehensive exam with its own question pool — 10 random questions, 80% to pass. Questions are different from module quizzes.',
    icon: '🎓',
    badge: { label: 'FINAL', cls: 'b-coral' },
  },
]
